export const  dummyEventsData = [
    {
        id: 1,
        title: 'North London vs West London',
        description: 'A friendly football match between North London and West London communities.',
        time: '3:00 PM',
        date: '2023-12-28',
        location: 'Finsbury Park, North London',
        ticketPrice: 5.99,
        currency: 'GBP',
    },
    {
        id: 2,
        title: 'Local Park Football Tournament',
        description: 'A neighborhood football tournament with teams from all over North London.',
        time: '2:30 PM',
        date: '2024-01-15',
        location: 'Hampstead Heath, North London',
        ticketPrice: 4.51,
        currency: 'GBP',
    },
    {
        id: 3,
        title: 'Community Football Match',
        description: 'North London community football match at Regent\'s Park.',
        time: '4:00 PM',
        date: '2024-02-10',
        location: 'Regent\'s Park, North London',
        ticketPrice: 3.99,
        currency: 'GBP',
    },
    {
        id: 4,
        title: 'Sunday Football League',
        description: 'Sunday league match featuring local teams from Islington and Camden.',
        time: '10:00 AM',
        date: '2024-03-05',
        location: 'Highbury Fields, North London',
        ticketPrice: 5.49,
        currency: 'GBP',
    },
    {
        id: 5,
        title: 'Big North London Derby',
        description: 'A highly anticipated derby match between two North London giants.',
        time: '7:30 PM',
        date: '2024-04-22',
        location: 'Alexandra Palace, North London',
        ticketPrice: 7.99,
        currency: 'GBP',
    },
    {
        id: 6,
        title: 'Youth Football Showcase',
        description: 'Showcasing young talent from North London in a friendly match.',
        time: '11:00 AM',
        date: '2024-05-18',
        location: 'Wembley Park, North London',
        ticketPrice: 3.99,
        currency: 'GBP',
    },
    {
        id: 7,
        title: 'North London Community Cup',
        description: 'Annual football tournament for the North London community.',
        time: '1:00 PM',
        date: '2024-06-12',
        location: 'Victoria Park, North London',
        ticketPrice: 4.99,
        currency: 'GBP',
    },
    {
        id: 8,
        title: 'North vs South London Showdown',
        description: 'A friendly match between North and South London teams.',
        time: '6:30 PM',
        date: '2024-07-20',
        location: 'Waterlow Park, North London',
        ticketPrice: 5.49,
        currency: 'GBP',
    },
    {
        id: 9,
        title: 'Summer Football Festival',
        description: 'A day-long football festival featuring multiple matches.',
        time: '9:00 AM',
        date: '2024-08-15',
        location: 'Primrose Hill, North London',
        ticketPrice: 6.99,
        currency: 'GBP',
    },
    {
        id: 10,
        title: 'North London Champions Cup',
        description: 'Championship match between the top teams in North London.',
        time: '7:00 PM',
        date: '2024-09-28',
        location: 'Hampstead Heath, North London',
        ticketPrice: 7.99,
        currency: 'GBP',
    },
    {
        id: 11,
        title: 'Local Park Football Tournament',
        description: 'A neighborhood football tournament with teams from all over North London.',
        time: '2:30 PM',
        date: '2024-10-15',
        location: 'Clissold Park, North London',
        ticketPrice: 4.51,
        currency: 'GBP',
    },
    {
        id: 12,
        title: 'Community Football Match',
        description: 'North London community football match at Regent\'s Park.',
        time: '4:00 PM',
        date: '2024-11-10',
        location: 'Finsbury Park, North London',
        ticketPrice: 3.99,
        currency: 'GBP',
    },
    {
        id: 13,
        title: 'Sunday Football League',
        description: 'Sunday league match featuring local teams from Islington and Camden.',
        time: '10:00 AM',
        date: '2024-12-05',
        location: 'Highbury Fields, North London',
        ticketPrice: 5.49,
        currency: 'GBP',
    },
    {
        id: 14,
        title: 'Big North London Derby',
        description: 'A highly anticipated derby match between two North London giants.',
        time: '7:30 PM',
        date: '2025-01-22',
        location: 'Alexandra Palace, North London',
        ticketPrice: 7.99,
        currency: 'GBP',
    },
    {
        id: 15,
        title: 'Youth Football Showcase',
        description: 'Showcasing young talent from North London in a friendly match.',
        time: '11:00 AM',
        date: '2025-02-18',
        location: 'Wembley Park, North London',
        ticketPrice: 3.99,
        currency: 'GBP',
    },
    {
        id: 16,
        title: 'North London Community Cup',
        description: 'Annual football tournament for the North London community.',
        time: '1:00 PM',
        date: '2025-03-12',
        location: 'Victoria Park, North London',
        ticketPrice: 4.99,
        currency: 'GBP',
    },
    {
        id: 17,
        title: 'North vs South London Showdown',
        description: 'A friendly match between North and South London teams.',
        time: '6:30 PM',
        date: '2025-04-20',
        location: 'Waterlow Park, North London',
        ticketPrice: 5.49,
        currency: 'GBP',
    },
    {
        id: 18,
        title: 'Summer Football Festival',
        description: 'A day-long football festival featuring multiple matches.',
        time: '9:00 AM',
        date: '2025-05-15',
        location: 'Primrose Hill, North London',
        ticketPrice: 6.99,
        currency: 'GBP',
    },
    {
        id: 19,
        title: 'North London Champions Cup',
        description: 'Championship match between the top teams in North London.',
        time: '7:00 PM',
        date: '2025-06-28',
        location: 'Hampstead Heath, North London',
        ticketPrice: 7.99,
        currency: 'GBP',
    },
    {
        id: 20,
        title: 'Local Park Football Tournament',
        description: 'A neighborhood football tournament with teams from all over North London.',
        time: '2:30 PM',
        date: '2025-07-15',
        location: 'Clissold Park, North London',
        ticketPrice: 4.51,
        currency: 'GBP',
    },
    {
        id: 21,
        title: 'Community Football Match',
        description: 'North London community football match at Regent\'s Park.',
        time: '4:00 PM',
        date: '2025-08-10',
        location: 'Finsbury Park, North London',
        ticketPrice: 3.99,
        currency: 'GBP',
    },
    {
        id: 22,
        title: 'Sunday Football League',
        description: 'Sunday league match featuring local teams from Islington and Camden.',
        time: '10:00 AM',
        date: '2025-09-05',
        location: 'Highbury Fields, North London',
        ticketPrice: 5.49,
        currency: 'GBP',
    },
    {
        id: 23,
        title: 'Big North London Derby',
        description: 'A highly anticipated derby match between two North London giants.',
        time: '7:30 PM',
        date: '2025-10-22',
        location: 'Alexandra Palace, North London',
        ticketPrice: 7.99,
        currency: 'GBP',
    },
    {
        id: 24,
        title: 'Youth Football Showcase',
        description: 'Showcasing young talent from North London in a friendly match.',
        time: '11:00 AM',
        date: '2025-11-18',
        location: 'Wembley Park, North London',
        ticketPrice: 3.99,
        currency: 'GBP',
    },
    {
        id: 25,
        title: 'North London Community Cup',
        description: 'Annual football tournament for the North London community.',
        time: '1:00 PM',
        date: '2025-12-12',
        location: 'Victoria Park, North London',
        ticketPrice: 4.99,
        currency: 'GBP',
    },
    {
        id: 26,
        title: 'North vs South London Showdown',
        description: 'A friendly match between North and South London teams.',
        time: '6:30 PM',
        date: '2026-01-20',
        location: 'Waterlow Park, North London',
        ticketPrice: 5.49,
        currency: 'GBP',
    },
    {
        id: 27,
        title: 'Summer Football Festival',
        description: 'A day-long football festival featuring multiple matches.',
        time: '9:00 AM',
        date: '2026-02-15',
        location: 'Primrose Hill, North London',
        ticketPrice: 6.99,
        currency: 'GBP',
    },
    {
        id: 28,
        title: 'North London Champions Cup',
        description: 'Championship match between the top teams in North London.',
        time: '7:00 PM',
        date: '2026-03-28',
        location: 'Hampstead Heath, North London',
        ticketPrice: 7.99,
        currency: 'GBP',
    },
    {
        id: 29,
        title: 'Local Park Football Tournament',
        description: 'A neighborhood football tournament with teams from all over North London.',
        time: '2:30 PM',
        date: '2026-04-15',
        location: 'Clissold Park, North London',
        ticketPrice: 4.51,
        currency: 'GBP',
    },
    {
        id: 30,
        title: 'Community Football Match',
        description: 'North London community football match at Regent\'s Park.',
        time: '4:00 PM',
        date: '2026-05-10',
        location: 'Finsbury Park, North London',
        ticketPrice: 3.99,
        currency: 'GBP',
    },
    {
        id: 31,
        title: 'Friendly Match at Markfield Park',
        description: 'A friendly football match at Markfield Park in Tottenham.',
        time: '2:00 PM',
        date: '2024-01-15',
        location: 'Markfield Park, Tottenham',
        ticketPrice: 4.99,
        currency: 'GBP',
    },
    {
        id: 32,
        title: 'Community Cup at Ponders End Park',
        description: 'A community football cup at Ponders End Park in Enfield.',
        time: '3:30 PM',
        date: '2024-02-20',
        location: 'Ponders End Park, Enfield',
        ticketPrice: 4.51,
        currency: 'GBP',
    },
    {
        id: 33,
        title: 'Local Park Tournament in North London',
        description: 'A local park tournament featuring North London teams.',
        time: '2:30 PM',
        date: '2024-03-10',
        location: 'Clissold Park, North London',
        ticketPrice: 3.99,
        currency: 'GBP',
    },
    {
        id: 34,
        title: 'Markfield Park Showdown',
        description: 'A showdown between local teams at Markfield Park in Tottenham.',
        time: '4:00 PM',
        date: '2024-04-12',
        location: 'Markfield Park, Tottenham',
        ticketPrice: 5.49,
        currency: 'GBP',
    },
    {
        id: 35,
        title: 'Ponders End Park Friendly Match',
        description: 'A friendly football match at Ponders End Park in Enfield.',
        time: '3:30 PM',
        date: '2024-05-18',
        location: 'Ponders End Park, Enfield',
        ticketPrice: 4.99,
        currency: 'GBP',
    },
    {
        id: 36,
        title: 'Community Cup at Clissold Park',
        description: 'A community football cup at Clissold Park in North London.',
        time: '2:00 PM',
        date: '2024-06-10',
        location: 'Clissold Park, North London',
        ticketPrice: 4.51,
        currency: 'GBP',
    },
    {
        id: 37,
        title: 'Tottenham vs Enfield Derby',
        description: 'A highly anticipated derby match between Tottenham and Enfield teams.',
        time: '7:00 PM',
        date: '2024-07-22',
        location: 'Markfield Park, Tottenham',
        ticketPrice: 7.99,
        currency: 'GBP',
    },
    {
        id: 38,
        title: 'North London Community Cup',
        description: 'Annual football tournament for the North London community.',
        time: '1:00 PM',
        date: '2024-01-28',
        location: 'Victoria Park, North London',
        ticketPrice: 4.99,
        currency: 'GBP',
    },
    {
        id: 39,
        title: 'Friendly Match at Markfield Park',
        description: 'A friendly football match at Markfield Park in Tottenham.',
        time: '2:00 PM',
        date: '2024-02-15',
        location: 'Markfield Park, Tottenham',
        ticketPrice: 4.99,
        currency: 'GBP',
    },
    {
        id: 40,
        title: 'Community Cup at Ponders End Park',
        description: 'A community football cup at Ponders End Park in Enfield.',
        time: '3:30 PM',
        date: '2024-03-20',
        location: 'Ponders End Park, Enfield',
        ticketPrice: 4.51,
        currency: 'GBP',
    },
    {
        id: 41,
        title: 'Local Park Tournament in North London',
        description: 'A local park tournament featuring North London teams.',
        time: '2:30 PM',
        date: '2024-04-10',
        location: 'Clissold Park, North London',
        ticketPrice: 3.99,
        currency: 'GBP',
    },
    {
        id: 42,
        title: 'Markfield Park Showdown',
        description: 'A showdown between local teams at Markfield Park in Tottenham.',
        time: '4:00 PM',
        date: '2024-05-12',
        location: 'Markfield Park, Tottenham',
        ticketPrice: 5.49,
        currency: 'GBP',
    },
    {
        id: 43,
        title: 'Ponders End Park Friendly Match',
        description: 'A friendly football match at Ponders End Park in Enfield.',
        time: '3:30 PM',
        date: '2024-06-18',
        location: 'Ponders End Park, Enfield',
        ticketPrice: 4.99,
        currency: 'GBP',
    },
    {
        id: 44,
        title: 'Community Cup at Clissold Park',
        description: 'A community football cup at Clissold Park in North London.',
        time: '2:00 PM',
        date: '2024-07-10',
        location: 'Clissold Park, North London',
        ticketPrice: 4.51,
        currency: 'GBP',
    },
    {
        id: 45,
        title: 'Tottenham vs Enfield Derby',
        description: 'A highly anticipated derby match between Tottenham and Enfield teams.',
        time: '7:00 PM',
        date: '2024-07-28',
        location: 'Markfield Park, Tottenham',
        ticketPrice: 7.99,
        currency: 'GBP',
    },
];