name: staged-preview
on:
  push:
    branches: [staged]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🖥️ EAS Update and Capture Output
        id: eas_update
        run: |
          OUTPUT=$(eas update --branch staged --message "staged")
          echo "$OUTPUT"
          UPDATE_GROUP_ID=$(echo "$OUTPUT" | awk -F'Update group ID    ' '/Update group ID/ {print $2}')
          echo "UPDATE_GROUP_ID=$UPDATE_GROUP_ID" >> $GITHUB_ENV
          eas channel:edit staged --branch staged
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      # - name: Generate Manifest URL
      #   run: echo "MANIFEST_URL=https://u.expo.dev/${{ secrets.EAS_PROJECT_ID }}?channel-name=production" >> $GITHUB_ENV

      # - name: Generate Deep Link
      #   run: echo "DEEP_LINK=exp+rijalclubapp://expo-development-client/?url=${{ env.MANIFEST_URL }}" >> $GITHUB_ENV

      - name: 🤮 Generate EXPO Go Deep Link
        run: echo "DEEP_EXPO_LINK=exp://u.expo.dev/${{ secrets.EAS_PROJECT_ID }}/group/${{ env.UPDATE_GROUP_ID }}" >> $GITHUB_ENV

      - name: ✍️ Update README.md with QR Code
        run: |
          sed -i "s|\(data=\)[^&]*|\1${{ env.DEEP_EXPO_LINK }}|" README.md

      - name: 🚲 Commit and push the changes to staged README.md
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update Expo QR Code and links in staged README"
          git push origin HEAD:staged
